WSUCEG-7140/mystore-teamDelta

- server/src/main/java/com/backend/server/controller/InventoryApis.java
- server/src/main/java/com/backend/server/repository/InventoryRepository.java
- server/src/main/java/com/backend/server/repository/UserRepository.java
- server/src/main/java/com/backend/server/service/InventoryService.java
- server/src/main/java/com/backend/server/service/InventoryServiceImpl.java
https://github.com/WSUCEG-7140/mystore-teamDelta/issues/13
> Added inventory logic to ad and update products

- server/src/main/java/com/backend/server/controller/InventoryApis.java
- server/src/main/java/com/backend/server/service/InventoryServiceImpl.java
https://github.com/WSUCEG-7140/mystore-teamDelta/issues/11
> Delta 11 Creating API endpoint to retrieve all products

- server/src/main/java/com/backend/server/controller/UserApis.java
- server/src/main/java/com/backend/server/service/UserService.java
- server/src/main/java/com/backend/server/service/UserServiceImpl.java
https://github.com/WSUCEG-7140/mystore-teamDelta/issues/12
> User registration API changes

- Meeting Minutes/06222023_1.txt
- Meeting Minutes/06282023_2.txt
- Meeting Minutes/07062023_3.txt
- Meeting Minutes/07132023_4.txt
- Meeting Minutes/07202023_5.txt
- Meeting Minutes/07202023_6.txt
I have added all our discussions over the period and uploading them. Please look into them.
> Uploading Meeting minutes

- server/src/main/java/com/backend/server/Model/Payment.java
- server/src/main/java/com/backend/server/Model/User.java
UserId cannot be primary key
made payment id as primary key and user id as forenId
> close #30 as a database developer write sql query to store the address and selected payment mode

- dataset/books.json
> close #20 as a developer add few products to database

- quick_shop/src/CSS/productDisplay.css
- quick_shop/src/components/productDisplay.js
created the Home page to display all the available products.
> close #18 as a UI developer i have to create a home page to show all products

- quick_shop/src/CSS/UserProfile.css
- quick_shop/src/components/UserProfile.js
added the user profile page and css styling for the same
> 34 as a UI developer design user profile page

- quick_shop/src/CSS/OrderView.css
- quick_shop/src/components/OrderView.js
> close #25 as a UI developer design my orders page

- server/src/main/java/com/backend/server/service/UserService.java
- server/src/main/java/com/backend/server/service/UserServiceImpl.java
Added the User cart Functionality
> close #26 as a database deveoper write sql query to store the cartwishlist products in database tables

- ER diagaram.txt
Adding ER diagram for the mystore application. In this diagram we are Showing relationship between tables that are used in database for the application development.
> ER diagram for mystore application

- quick_shop/src/CSS/ProductSearch.css
- quick_shop/src/components/ProductSearch.js
Added the product search functionality to search the products.
> close #3 as a UI developer adding search feature to the webpage for the user to search for products

- quick_shop/src/CSS/PaymentTransaction.css
- quick_shop/src/components/PaymentTransaction.js
Added the Transaction page to display the payment details.
> close #31 as a UI developer design transaction page

- quick_shop/src/CSS/LoginPage.csss
- quick_shop/src/components/LoginPage.js
> close #1 as a UI developer i want to develop a login page so that the user can login

- README.md
> close #59 Added user documentation

- README.md
> 43 as a student fix the issues if found in project

- .github/workflows/maven.yml
> close #10 configure automated testing and documentation

- quick_shop/src/CSS/PlaceOrderPage.css
- quick_shop/src/components/PlaceOrderPage.js
Added the css and js file for the place order page
> close #28 as a UI developer i want to create a place order page

- server/src/main/java/com/backend/server/Model/Payment.java
- server/src/main/java/com/backend/server/repository/PaymentRepository.java
- server/src/main/java/com/backend/server/service/PaymentService.java
- server/src/main/java/com/backend/server/service/PaymentServiceImpl.java
Added th epayment functionality
> close #33 as a database developer write sql query to store the payment details

- server/src/main/java/com/backend/server/Model/Inventory.java
Adding comments for Inventory.java
> Update comments for Inventory.java

- quick_shop/src/CSS/AppBar.css
Adding comments and issue number to App Bar html page
> Update Comments to AppBar.css page

- quick_shop/pages/checkout.jsx
Adding comments to the checkout page
> Update comments for checkout.jsx

- quick_shop/src/App.css
- quick_shop/src/App.js
- quick_shop/src/App.test.js
- quick_shop/src/CSS/AppBarOptionsDescriptions.css
- quick_shop/src/CSS/Carousel.css
- quick_shop/src/CSS/DynamicList.css
- quick_shop/src/CSS/LoginPage.csss
- quick_shop/src/CSS/OrderView.css
- quick_shop/src/CSS/PaymentTransaction.css
- quick_shop/src/CSS/PlaceOrderPage.css
- quick_shop/src/CSS/ProductSearch.css
- quick_shop/src/CSS/Screen.css
- quick_shop/src/CSS/SearchBar.css
- quick_shop/src/CSS/UserProfile.css
- quick_shop/src/CSS/productDisplay.css
- quick_shop/src/index.css
- quick_shop/src/index.js
- server/src/main/java/com/backend/server/ServerApplication.java
Adding comments in .CSS files.
> Updating Comments to CSS files

- quick_shop/src/components/Wishlist.js
Added all the required functionality for the wishlist functionality
> Added wishlist changes to the code and added the api call functionality

- server/src/main/java/com/backend/server/controller/InventoryApis.java
Added changes for health status in Inventory API for Issue
> Added changes for health status in Inventory API

- server/src/main/java/com/backend/server/controller/UserApis.java
UserAPI health check Added the getHelath method()
> 89 create health endpoint for inventory api

- server/src/main/java/com/backend/server/controller/InventoryApis.java
Added transaction details using the payment data (32)
> Added transaction details using the payment data
